#!/bin/bash

g++ StlContainers.cpp -lboost_python -lpython2.6 -I /usr/include/python2.6 -o StlContainers.so -shared
g++ Embedded_python_test.cpp -lboost_python -lpython2.6 -I /usr/include/python2.6 -o zpr

